server.port: 8085
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.task-tracker.project: info
    org.springframework.web.servlet: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
springdoc:
  show-actuator: true
spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
  application.name: project
  datasource:
    url: ${LOCAL_DB_NAME}
    username: ${LOCAL_USER_NAME}
    password: ${LOCAL_USER_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    cache: false
    decoupled-logic: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
    prefix=file: src/main/resources/templates/
---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
